-- 1. Create student_attendance table
CREATE TABLE IF NOT EXISTS public.student_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint REFERENCES public.students(id) ON DELETE CASCADE,
    class_name text NOT NULL,
    date date NOT NULL DEFAULT CURRENT_DATE,
    status text NOT NULL CHECK (status IN ('present', 'absent', 'late')),
    marked_by bigint REFERENCES public.teachers(id) ON DELETE SET NULL,
    marked_at time with time zone DEFAULT CURRENT_TIME,
    created_at timestamp with time zone DEFAULT now()
);
-- Disable security for this table so our apps can read/write directly
ALTER TABLE public.student_attendance DISABLE ROW LEVEL SECURITY;

-- 2. Create staff_attendance table
CREATE TABLE IF NOT EXISTS public.staff_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL,
    person_type text NOT NULL CHECK (person_type IN ('teacher', 'staff')),
    school_id text NOT NULL DEFAULT 'SCH_MH_27430012',
    date date NOT NULL DEFAULT CURRENT_DATE,
    status text NOT NULL CHECK (status IN ('present', 'absent', 'half_day', 'leave')),
    marked_by text,
    created_at timestamp with time zone DEFAULT now()
);
-- Disable security for this table so our apps can read/write directly
ALTER TABLE public.staff_attendance DISABLE ROW LEVEL SECURITY;

-- 3. Create marks table
CREATE TABLE IF NOT EXISTS public.marks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint REFERENCES public.students(id) ON DELETE CASCADE,
    school_id text DEFAULT 'SCH_MH_27430012',
    class_name text NOT NULL,
    subject text NOT NULL,
    test_name text NOT NULL,
    test_type text NOT NULL CHECK (test_type IN ('unit', 'weekly', 'monthly', 'olympiad', 'semester')),
    date date NOT NULL DEFAULT CURRENT_DATE,
    max_marks numeric NOT NULL,
    marks_obtained numeric NOT NULL,
    grade text,
    teacher_id bigint REFERENCES public.teachers(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now()
);
-- Disable security for this table so our apps can read/write directly
ALTER TABLE public.marks DISABLE ROW LEVEL SECURITY;

-- 4. Create homework table
CREATE TABLE IF NOT EXISTS public.homework (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id text DEFAULT 'SCH_MH_27430012',
    class_name text NOT NULL,
    teacher_id bigint REFERENCES public.teachers(id) ON DELETE CASCADE,
    subject text NOT NULL,
    assigned_date date NOT NULL DEFAULT CURRENT_DATE,
    due_date date NOT NULL,
    content_type text NOT NULL CHECK (content_type IN ('text', 'photo', 'voice', 'preloaded')),
    text_content text,
    photo_url text,
    voice_url text,
    chapter_no integer,
    chapter_name text,
    created_at timestamp with time zone DEFAULT now()
);
-- Disable security for this table so our apps can read/write directly
ALTER TABLE public.homework DISABLE ROW LEVEL SECURITY;
